global:
  scrape_interval: 10s

scrape_configs:
  - job_name: "filial-api-actuator"
    scrape_interval: 5s
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ['host.docker.internal:8080']     
