spring:
   application:
      name: filial-api           
   profiles:      
      active: dev
   jpa:
      properties:
         hibernate:
            show_sql: true
            use_sql_coments: true
            format_sql: true
            type: trace

management:
   endpoints:
      web:
         exposure:
            include: info, health, metrics, prometheus